### ISSUE TITLE
no 720p any more with Kodi 18

### ISSUE THREAD

**Issue by usphil** [nightflyer73/plugin.video.supertennis#1]
I just upgraded my system from LibreElec 8 to LibreElec 9 as same as Kodi 18 on the PC
The resolution I get from Kodi 17 is 720
But on Kodi 18 the resolution is very low. I think it's real low, lower than 480!

Is there any way to set the Super Tennis resolution?

Thank you!

**Comment by nightflyer73** [comment]
This is not an addon problem. It is Kodi that select what it thinks it is the best suitable stream.
